// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qowgpyakcsrybksyziot.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvd2dweWFrY3NyeWJrc3l6aW90Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2NDg5NTgsImV4cCI6MjA2OTIyNDk1OH0.NVvXPiSy7YsgoSo2-SdRsW_aS0fBBXALKGzUdLdt6_8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: {
      Accept: 'application/json',
    },
  },
  db: {
    schema: 'public',
  },
});